version: '3'

services:
  sortingmethods:
    build: .
    command: make run_app
    volumes:
      - .:/var/www/sorting_methods
      - bundle-data:/var/www/bundle
volumes:
  bundle-data:
    driver: local